[package]
name = "nimue"
version = "0.0.1-alpha2"
authors = ["Michele Orrù <michele@tumbolandia.net>"]
description = "A library for secure Fiat-Shamir."
edition = "2021"
license = "MIT/Apache-2.0"
resolver = "2"

[dependencies]
zeroize = "1.6.0"
rand = {version="0.8.5", features=["getrandom"]}
digest = "0.10.7"
generic-array = "0.14.7"
# used as default hasher for the prover
keccak = "0.1.4"

# dependencies for arkworks
ark-ff = {version="0.4.0", optional=true}
ark-ec = {version="0.4.0", optional=true}
ark-serialize = {version="0.4.2", optional=true}
ark-crypto-primitives = {version="0.4.0", optional=true}
serde = "1.0.164"
bincode = "1.3.3"
log = "0.4.20"

[features]
default = ["arkworks"]
arkworks = ["dep:ark-ff", "dep:ark-ec", "dep:ark-serialize", "dep:ark-crypto-primitives"]

[dev-dependencies]
ark-bls12-381 = "0.4.0"
ark-std = "0.4.0"
sha2 = "0.10.7"
blake2 = "0.10.6"
